### ISSUE TITLE
Wrong commands for SD9

### ISSUE THREAD

**Issue by mjbendixen** [castles/OSCWebMixer#4]
Hey there

Had to change mapping from "/sd/Input_Channels/" to "/Input_Channels/" to get messages, and that works, however the value of the volume slider in webmixer is 0-1, but the commands going to the console needs to be from -150 to +10. how can i fix this ?

Thansks, Martin

**Comment by castles** [comment]
Thats interesting.. perhaps your OSC implementation is different to what I was provided from my Digico Rep. Are you using Stealth Core 2? Are you using the OTH OSC SD8-SD9-SD11.dosc OSC extension?

**Comment by mjbendixen** [comment]
Hmm. I been trying on the ipad commands. And it looks like the console is missing the oth osc commands. Yes im running core2 v1619

**Comment by castles** [comment]
Ok, check with your rep and let me know if you get stuck. I might be able to send you what I have.

**Comment by mjbendixen** [comment]
Just for info, got it working after talking to digico support, the OTH osc command list is not on the console as default, but got it from him.

Great little piece of software :)

If you would like the OTH OSC commands .docs, to include here, let me know, i can share it with you.

Best Martin

**Comment by castles** [comment]
Awesome, I'm glad you got it working.

Yes, please share it. I'm interested to see if your version has changed in anyway to ours. I was provided it a few years ago.

Also, what folder did you put the file in on the desk? It was so long ago that I don't remember this step and I would like to add this to the instructions.

**Comment by mjbendixen** [comment]
I have attached the .zip from Digico, with the complete OTH OSC guide and files.

The file goes on the app drive in the SDx folder, usually drive D:/SD9/

[DiGiCo_Other_OSC_Package_V987.zip](https://github.com/castles/OSCWebMixer/files/10800999/DiGiCo_Other_OSC_Package_V987.zip)

**Comment by castles** [comment]
Thanks. It looks like the file I built webmixer for is the same as yours. I was never provided that pdf with all the commands. That would have come in handy!

I will update the instructions now and include this zip.
