### ISSUE TITLE
Loading desk values gets stuck at 90%

### ISSUE THREAD

**Issue by luprchal** [castles/OSCWebMixer#5]
Hi,

I installed on Raspbian on RPi 3B. For testing, instead of a console I have used SD9 Offline editor on Win10.
All works fine with the default config, however, the loading desk values gets stuck at cca 90%, right after the last channel name is loaded, when I use my custom config.

Can you please help?

This is my default.json:

```
{
	"desk": {
		"type": "SD",
		"ip": "192.168.1.186",
		"receive_port": 8080,
		"send_port": 9090
	},
	"server": {
		"port" : 9000
	},
	"aux": [
		{
			"label": "Alice",
			"channel": 1,
			"stereo": false,
			"colour": "6, 106, 166"
		},
		{
			"label": "Merun",
			"channel": 2,
			"stereo": false,
			"colour": "6, 166, 99"
		},
		{
			"label": "Marta",
			"channel": 3,
			"stereo": false,
			"colour": "48, 213, 6"
		},
		{
			"label": "Michal",
			"channel": 4,
			"stereo": false,
			"colour": "166, 6, 6"
		},
		{
			"label": "Stepan",
			"channel": 5,
			"stereo": false,
			"colour": "113, 6, 166"
		},
		{
			"label": "Wajsar",
			"channel": 5,
			"stereo": false,
			"colour": "113, 6, 166"
		}
	],
	"channels" : [37,38,39,40,41,42,
				  25,26,
				  43,44,45,46,47,48,
				  49,50,51,52,53,54
	]
}

```

**Comment by castles** [comment]
Hi, 

Your formatting appears to be correct. I'm guessing you might have your channel number wrong. Maybe try doing one channel at a time and see if you can find the invalid number.

If that fails, try testing your config with only one AUX and see if it loads.

**Comment by luprchal** [comment]
Hi, thanks for your response. There was an error in the config - AUX 5 was defined twice (5th and 6th position).
Maybe this is something that could be sanitized before loading the desk values.

**Comment by castles** [comment]
Thanks for reporting this. I have added pushed an update to help prevent this from happening again.
